Milestone3 review
Byabasaija/bookstore_app pull request #4
Opened 2021-07-06 20:38 UTC by Byabasaija

In this milestone we,
- Implemented the add book functionality to the store
- Implemented the remove book functionality to the store
A user can therefore and multiple books to the store and also is able to remove/delete books from the store.

2021-07-06 21:45 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi team! Your work so far is commendable! :+1: However, there is just one requirement I'd suggest you look into before having your PR approved i.e.

- [ ] Check out the code comment below about your implementation of the `handleRemoveBook` method. ([screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png))

_Please make the necessary changes and submit another code review request._
__[Treasure Kabareebe](https://trekab.github.io)__

2021-07-06 21:45 UTC, trekab commented on src/components/Book.js
> +  };
This method is expected to be implemented in the `BookList` component and passed down to the book as a prop. [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png)

2021-07-07 10:51 UTC, Elbie-em approved these changes
## STATUS: APPROVED ✅ 

Hi @Byabasaija and @saimaAnis21, congratulations on your great effort in applying the changes requested. You can proceed to the next milestone.

### [OPTIONAL]
- [ ] Check my comments below to apply some optional changes

*All the best* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-07 10:51 UTC, Elbie-em commented on src/containers/BooksList.js
- [ ] Consider destructuring your props in a single line, this makes the code look more clean and professional.
       ` const { books , removeBook} = props   OR  const BookList = ({books, removeBook}) => {....}`

2021-07-07 11:00 UTC, merged